# General
fullscreen=yes
keep-open=yes
save-position-on-quit=yes
force-seekable=yes
cursor-autohide=1000
autocreate-playlist=same

# OSD
osd-level=1

# Screenshot
screenshot-sw=yes
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-jpeg-quality=100
screenshot-dir=~/Pictures/mpvScreenshots
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"

# Priority (Language priority)
slang=eng,en,en-en,en-orig,english
alang=jp,jpn,japanese,en,eng,english

# Video
hwdec=yes

# Audio
audio-delay=+0.084

# Subs
sub-visibility=yes
demuxer-mkv-subtitle-preroll=yes
sub-auto-exts=srt,ass,txt
subs-with-matching-audio=no
blend-subtitles=yes
sub-fix-timing=yes
sub-auto=fuzzy
sub-ass-override=scale
sub-pos=100
sub-scale=1

ytdl-format="worstvideo[height<=?1080]+worstaudio[acodec=opus]/worstvideo[height<=?1080]+bestaudio"
