# arrow keys
UP add volume 5
DOWN add volume -5
RIGHT seek 10; show-text "Seek: +10s | ${time-pos} / ${duration} (${percent-pos}%)"
LEFT seek -10; show-text "Seek: -10s | ${time-pos} / ${duration} (${percent-pos}%)"
Ctrl+RIGHT seek 60; show-text "Seek: +60s | ${time-pos} / ${duration} (${percent-pos}%)"
Ctrl+LEFT seek -60; show-text "Seek: -60s | ${time-pos} / ${duration} (${percent-pos}%)"
Shift+RIGHT seek 5; show-text "Seek: +5s | ${time-pos} / ${duration} (${percent-pos}%)"
Shift+LEFT seek -5; show-text "Seek: -5s | ${time-pos} / ${duration} (${percent-pos}%)"

# mouse
MBTN_LEFT ignore
MBTN_RIGHT cycle pause
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5
MBTN_LEFT_DBL cycle fullscreen

# subs and audio delays and mute
g add sub-delay -0.05
h add sub-delay 0.05
j add audio-delay -0.05
k add audio-delay 0.05
m cycle mute
] add speed 0.1
[ add speed -0.1
ESC cycle fullscreen
q quit-watch-later
Ctrl+q quit
v cycle sub
Shift+v cycle sub down
b cycle audio-track
Shift+b cycle audio-track down
e frame-step
Shift+e frame-back-step
o cycle-values video-unscaled yes no
a cycle-values video-aspect-override -1 16:9 4:3 16:10 2.35:1 2.40:1 1.85:1 1:1
Shift+a set video-aspect-override -1
c cycle-values video-crop "" 16:9 4:3 16:10 2.35:1 1.85:1 1:1
Shift+c set video-crop ""
f cycle fullscreen
1 add chapter -1
2 add chapter 1
Shift+UP add sub-pos -1
Shift+DOWN add sub-pos +1
= add sub-scale +0.1
- add sub-scale -0.1
